// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/cli/v1/cli.proto

package cli

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CLI command annotation for RPC methods
// Customizes command name and help text following urfave/cli v3 best practices
type CommandOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Custom name for the command (defaults to kebab-case of method name)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Short one-line description shown in command lists and help summaries
	// Best practice: Keep concise (e.g., "retrieve a user by ID")
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Longer, detailed explanation of the command
	// Use this for multi-paragraph documentation, examples, and detailed behavior
	LongDescription string `protobuf:"bytes,3,opt,name=long_description,json=longDescription,proto3" json:"long_description,omitempty"`
	// Custom usage text to override the auto-generated USAGE line
	// Example: "get-user [options] <user-id>"
	UsageText string `protobuf:"bytes,4,opt,name=usage_text,json=usageText,proto3" json:"usage_text,omitempty"`
	// Description of arguments this command accepts
	// Example: "<user-id>" or "[filter-expression]"
	ArgsUsage     string `protobuf:"bytes,5,opt,name=args_usage,json=argsUsage,proto3" json:"args_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOptions) Reset() {
	*x = CommandOptions{}
	mi := &file_proto_cli_v1_cli_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOptions) ProtoMessage() {}

func (x *CommandOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_v1_cli_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOptions.ProtoReflect.Descriptor instead.
func (*CommandOptions) Descriptor() ([]byte, []int) {
	return file_proto_cli_v1_cli_proto_rawDescGZIP(), []int{0}
}

func (x *CommandOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CommandOptions) GetLongDescription() string {
	if x != nil {
		return x.LongDescription
	}
	return ""
}

func (x *CommandOptions) GetUsageText() string {
	if x != nil {
		return x.UsageText
	}
	return ""
}

func (x *CommandOptions) GetArgsUsage() string {
	if x != nil {
		return x.ArgsUsage
	}
	return ""
}

// CLI flag annotation for message fields
// Maps message fields to CLI flags
type FlagOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shorthand     string                 `protobuf:"bytes,2,opt,name=shorthand,proto3" json:"shorthand,omitempty"`
	Usage         string                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagOptions) Reset() {
	*x = FlagOptions{}
	mi := &file_proto_cli_v1_cli_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagOptions) ProtoMessage() {}

func (x *FlagOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_v1_cli_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagOptions.ProtoReflect.Descriptor instead.
func (*FlagOptions) Descriptor() ([]byte, []int) {
	return file_proto_cli_v1_cli_proto_rawDescGZIP(), []int{1}
}

func (x *FlagOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlagOptions) GetShorthand() string {
	if x != nil {
		return x.Shorthand
	}
	return ""
}

func (x *FlagOptions) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *FlagOptions) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

// Service options annotation
// Defines CLI customization for a service following urfave/cli v3 best practices
type ServiceOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Custom name for the service command (defaults to kebab-case of service name)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Short one-line description shown in service lists
	// Best practice: Keep concise (e.g., "user management commands")
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Longer, detailed explanation of the service
	// Use this for multi-paragraph documentation and service overview
	LongDescription string `protobuf:"bytes,3,opt,name=long_description,json=longDescription,proto3" json:"long_description,omitempty"`
	// Custom usage text to override the auto-generated USAGE line
	UsageText string `protobuf:"bytes,4,opt,name=usage_text,json=usageText,proto3" json:"usage_text,omitempty"`
	// Description of arguments this service accepts
	ArgsUsage     string `protobuf:"bytes,5,opt,name=args_usage,json=argsUsage,proto3" json:"args_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_proto_cli_v1_cli_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_v1_cli_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_proto_cli_v1_cli_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceOptions) GetLongDescription() string {
	if x != nil {
		return x.LongDescription
	}
	return ""
}

func (x *ServiceOptions) GetUsageText() string {
	if x != nil {
		return x.UsageText
	}
	return ""
}

func (x *ServiceOptions) GetArgsUsage() string {
	if x != nil {
		return x.ArgsUsage
	}
	return ""
}

// Service config annotation
// Defines the configuration message type for a service
type ServiceConfigOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the config message type (must be in same package)
	ConfigMessage string `protobuf:"bytes,1,opt,name=config_message,json=configMessage,proto3" json:"config_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfigOptions) Reset() {
	*x = ServiceConfigOptions{}
	mi := &file_proto_cli_v1_cli_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfigOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfigOptions) ProtoMessage() {}

func (x *ServiceConfigOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_v1_cli_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfigOptions.ProtoReflect.Descriptor instead.
func (*ServiceConfigOptions) Descriptor() ([]byte, []int) {
	return file_proto_cli_v1_cli_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceConfigOptions) GetConfigMessage() string {
	if x != nil {
		return x.ConfigMessage
	}
	return ""
}

// Enum value annotation
// Allows customizing the CLI name for enum values
type EnumValueOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Custom CLI name for this enum value (defaults to enum value name)
	// Example: For LogLevel.DEBUG, you might use "debug" or "verbose"
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValueOptions) Reset() {
	*x = EnumValueOptions{}
	mi := &file_proto_cli_v1_cli_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueOptions) ProtoMessage() {}

func (x *EnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cli_v1_cli_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValueOptions.ProtoReflect.Descriptor instead.
func (*EnumValueOptions) Descriptor() ([]byte, []int) {
	return file_proto_cli_v1_cli_proto_rawDescGZIP(), []int{4}
}

func (x *EnumValueOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var file_proto_cli_v1_cli_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*CommandOptions)(nil),
		Field:         50001,
		Name:          "cli.v1.command",
		Tag:           "bytes,50001,opt,name=command",
		Filename:      "proto/cli/v1/cli.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FlagOptions)(nil),
		Field:         50002,
		Name:          "cli.v1.flag",
		Tag:           "bytes,50002,opt,name=flag",
		Filename:      "proto/cli/v1/cli.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         50000,
		Name:          "cli.v1.service",
		Tag:           "bytes,50000,opt,name=service",
		Filename:      "proto/cli/v1/cli.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceConfigOptions)(nil),
		Field:         50003,
		Name:          "cli.v1.service_config",
		Tag:           "bytes,50003,opt,name=service_config",
		Filename:      "proto/cli/v1/cli.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueOptions)(nil),
		Field:         50004,
		Name:          "cli.v1.enum_value",
		Tag:           "bytes,50004,opt,name=enum_value",
		Filename:      "proto/cli/v1/cli.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional cli.v1.CommandOptions command = 50001;
	E_Command = &file_proto_cli_v1_cli_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional cli.v1.FlagOptions flag = 50002;
	E_Flag = &file_proto_cli_v1_cli_proto_extTypes[1]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional cli.v1.ServiceOptions service = 50000;
	E_Service = &file_proto_cli_v1_cli_proto_extTypes[2]
	// optional cli.v1.ServiceConfigOptions service_config = 50003;
	E_ServiceConfig = &file_proto_cli_v1_cli_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional cli.v1.EnumValueOptions enum_value = 50004;
	E_EnumValue = &file_proto_cli_v1_cli_proto_extTypes[4]
)

var File_proto_cli_v1_cli_proto protoreflect.FileDescriptor

const file_proto_cli_v1_cli_proto_rawDesc = "" +
	"\n" +
	"\x16proto/cli/v1/cli.proto\x12\x06cli.v1\x1a google/protobuf/descriptor.proto\"\xaf\x01\n" +
	"\x0eCommandOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12)\n" +
	"\x10long_description\x18\x03 \x01(\tR\x0flongDescription\x12\x1d\n" +
	"\n" +
	"usage_text\x18\x04 \x01(\tR\tusageText\x12\x1d\n" +
	"\n" +
	"args_usage\x18\x05 \x01(\tR\targsUsage\"q\n" +
	"\vFlagOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tshorthand\x18\x02 \x01(\tR\tshorthand\x12\x14\n" +
	"\x05usage\x18\x03 \x01(\tR\x05usage\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\"\xaf\x01\n" +
	"\x0eServiceOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12)\n" +
	"\x10long_description\x18\x03 \x01(\tR\x0flongDescription\x12\x1d\n" +
	"\n" +
	"usage_text\x18\x04 \x01(\tR\tusageText\x12\x1d\n" +
	"\n" +
	"args_usage\x18\x05 \x01(\tR\targsUsage\"=\n" +
	"\x14ServiceConfigOptions\x12%\n" +
	"\x0econfig_message\x18\x01 \x01(\tR\rconfigMessage\"&\n" +
	"\x10EnumValueOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:R\n" +
	"\acommand\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\v2\x16.cli.v1.CommandOptionsR\acommand:H\n" +
	"\x04flag\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\v2\x13.cli.v1.FlagOptionsR\x04flag:S\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18І\x03 \x01(\v2\x16.cli.v1.ServiceOptionsR\aservice:f\n" +
	"\x0eservice_config\x12\x1f.google.protobuf.ServiceOptions\x18ӆ\x03 \x01(\v2\x1c.cli.v1.ServiceConfigOptionsR\rserviceConfig:\\\n" +
	"\n" +
	"enum_value\x12!.google.protobuf.EnumValueOptions\x18Ԇ\x03 \x01(\v2\x18.cli.v1.EnumValueOptionsR\tenumValueB0Z.github.com/drewfead/proto-cli/proto/cli/v1;clib\x06proto3"

var (
	file_proto_cli_v1_cli_proto_rawDescOnce sync.Once
	file_proto_cli_v1_cli_proto_rawDescData []byte
)

func file_proto_cli_v1_cli_proto_rawDescGZIP() []byte {
	file_proto_cli_v1_cli_proto_rawDescOnce.Do(func() {
		file_proto_cli_v1_cli_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cli_v1_cli_proto_rawDesc), len(file_proto_cli_v1_cli_proto_rawDesc)))
	})
	return file_proto_cli_v1_cli_proto_rawDescData
}

var file_proto_cli_v1_cli_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_cli_v1_cli_proto_goTypes = []any{
	(*CommandOptions)(nil),                // 0: cli.v1.CommandOptions
	(*FlagOptions)(nil),                   // 1: cli.v1.FlagOptions
	(*ServiceOptions)(nil),                // 2: cli.v1.ServiceOptions
	(*ServiceConfigOptions)(nil),          // 3: cli.v1.ServiceConfigOptions
	(*EnumValueOptions)(nil),              // 4: cli.v1.EnumValueOptions
	(*descriptorpb.MethodOptions)(nil),    // 5: google.protobuf.MethodOptions
	(*descriptorpb.FieldOptions)(nil),     // 6: google.protobuf.FieldOptions
	(*descriptorpb.ServiceOptions)(nil),   // 7: google.protobuf.ServiceOptions
	(*descriptorpb.EnumValueOptions)(nil), // 8: google.protobuf.EnumValueOptions
}
var file_proto_cli_v1_cli_proto_depIdxs = []int32{
	5,  // 0: cli.v1.command:extendee -> google.protobuf.MethodOptions
	6,  // 1: cli.v1.flag:extendee -> google.protobuf.FieldOptions
	7,  // 2: cli.v1.service:extendee -> google.protobuf.ServiceOptions
	7,  // 3: cli.v1.service_config:extendee -> google.protobuf.ServiceOptions
	8,  // 4: cli.v1.enum_value:extendee -> google.protobuf.EnumValueOptions
	0,  // 5: cli.v1.command:type_name -> cli.v1.CommandOptions
	1,  // 6: cli.v1.flag:type_name -> cli.v1.FlagOptions
	2,  // 7: cli.v1.service:type_name -> cli.v1.ServiceOptions
	3,  // 8: cli.v1.service_config:type_name -> cli.v1.ServiceConfigOptions
	4,  // 9: cli.v1.enum_value:type_name -> cli.v1.EnumValueOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	5,  // [5:10] is the sub-list for extension type_name
	0,  // [0:5] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cli_v1_cli_proto_init() }
func file_proto_cli_v1_cli_proto_init() {
	if File_proto_cli_v1_cli_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cli_v1_cli_proto_rawDesc), len(file_proto_cli_v1_cli_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_proto_cli_v1_cli_proto_goTypes,
		DependencyIndexes: file_proto_cli_v1_cli_proto_depIdxs,
		MessageInfos:      file_proto_cli_v1_cli_proto_msgTypes,
		ExtensionInfos:    file_proto_cli_v1_cli_proto_extTypes,
	}.Build()
	File_proto_cli_v1_cli_proto = out.File
	file_proto_cli_v1_cli_proto_goTypes = nil
	file_proto_cli_v1_cli_proto_depIdxs = nil
}
