// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: examples/simple/example.proto

package simple

import (
	_ "github.com/drewfead/proto-cli/internal/clipb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogLevel enum for configuration
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_DEBUG                 LogLevel = 1
	LogLevel_INFO                  LogLevel = 2
	LogLevel_WARN                  LogLevel = 3
	LogLevel_ERROR                 LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "DEBUG",
		2: "INFO",
		3: "WARN",
		4: "ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"DEBUG":                 1,
		"INFO":                  2,
		"WARN":                  3,
		"ERROR":                 4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_simple_example_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_examples_simple_example_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_examples_simple_example_proto_rawDescGZIP(), []int{0}
}

// DatabaseConfig is a nested configuration message
type DatabaseConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Url            string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	MaxConnections int32                  `protobuf:"varint,2,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DatabaseConfig) Reset() {
	*x = DatabaseConfig{}
	mi := &file_examples_simple_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseConfig) ProtoMessage() {}

func (x *DatabaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simple_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseConfig.ProtoReflect.Descriptor instead.
func (*DatabaseConfig) Descriptor() ([]byte, []int) {
	return file_examples_simple_example_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DatabaseConfig) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *DatabaseConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// PostgresBackend configuration
type PostgresBackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Database      string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresBackend) Reset() {
	*x = PostgresBackend{}
	mi := &file_examples_simple_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresBackend) ProtoMessage() {}

func (x *PostgresBackend) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simple_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresBackend.ProtoReflect.Descriptor instead.
func (*PostgresBackend) Descriptor() ([]byte, []int) {
	return file_examples_simple_example_proto_rawDescGZIP(), []int{1}
}

func (x *PostgresBackend) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PostgresBackend) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PostgresBackend) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

// MySQLBackend configuration
type MySQLBackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Database      string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	EnableSsl     bool                   `protobuf:"varint,4,opt,name=enable_ssl,json=enableSsl,proto3" json:"enable_ssl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MySQLBackend) Reset() {
	*x = MySQLBackend{}
	mi := &file_examples_simple_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MySQLBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySQLBackend) ProtoMessage() {}

func (x *MySQLBackend) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simple_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySQLBackend.ProtoReflect.Descriptor instead.
func (*MySQLBackend) Descriptor() ([]byte, []int) {
	return file_examples_simple_example_proto_rawDescGZIP(), []int{2}
}

func (x *MySQLBackend) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *MySQLBackend) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *MySQLBackend) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *MySQLBackend) GetEnableSsl() bool {
	if x != nil {
		return x.EnableSsl
	}
	return false
}

// UserServiceConfig defines configuration for UserService
type UserServiceConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DatabaseUrl    string                 `protobuf:"bytes,1,opt,name=database_url,json=databaseUrl,proto3" json:"database_url,omitempty"`
	MaxConnections int64                  `protobuf:"varint,2,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	// Nested message field
	Database *DatabaseConfig `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	// Enum field
	LogLevel LogLevel `protobuf:"varint,4,opt,name=log_level,json=logLevel,proto3,enum=example.LogLevel" json:"log_level,omitempty"`
	// Repeated field
	AllowedOrigins []string `protobuf:"bytes,5,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowed_origins,omitempty"`
	// Map field
	FeatureFlags map[string]string `protobuf:"bytes,6,rep,name=feature_flags,json=featureFlags,proto3" json:"feature_flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Oneof (union type)
	//
	// Types that are valid to be assigned to Backend:
	//
	//	*UserServiceConfig_Postgres
	//	*UserServiceConfig_Mysql
	Backend       isUserServiceConfig_Backend `protobuf_oneof:"backend"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceConfig) Reset() {
	*x = UserServiceConfig{}
	mi := &file_examples_simple_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceConfig) ProtoMessage() {}

func (x *UserServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simple_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceConfig.ProtoReflect.Descriptor instead.
func (*UserServiceConfig) Descriptor() ([]byte, []int) {
	return file_examples_simple_example_proto_rawDescGZIP(), []int{3}
}

func (x *UserServiceConfig) GetDatabaseUrl() string {
	if x != nil {
		return x.DatabaseUrl
	}
	return ""
}

func (x *UserServiceConfig) GetMaxConnections() int64 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *UserServiceConfig) GetDatabase() *DatabaseConfig {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *UserServiceConfig) GetLogLevel() LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *UserServiceConfig) GetAllowedOrigins() []string {
	if x != nil {
		return x.AllowedOrigins
	}
	return nil
}

func (x *UserServiceConfig) GetFeatureFlags() map[string]string {
	if x != nil {
		return x.FeatureFlags
	}
	return nil
}

func (x *UserServiceConfig) GetBackend() isUserServiceConfig_Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *UserServiceConfig) GetPostgres() *PostgresBackend {
	if x != nil {
		if x, ok := x.Backend.(*UserServiceConfig_Postgres); ok {
			return x.Postgres
		}
	}
	return nil
}

func (x *UserServiceConfig) GetMysql() *MySQLBackend {
	if x != nil {
		if x, ok := x.Backend.(*UserServiceConfig_Mysql); ok {
			return x.Mysql
		}
	}
	return nil
}

type isUserServiceConfig_Backend interface {
	isUserServiceConfig_Backend()
}

type UserServiceConfig_Postgres struct {
	Postgres *PostgresBackend `protobuf:"bytes,7,opt,name=postgres,proto3,oneof"`
}

type UserServiceConfig_Mysql struct {
	Mysql *MySQLBackend `protobuf:"bytes,8,opt,name=mysql,proto3,oneof"`
}

func (*UserServiceConfig_Postgres) isUserServiceConfig_Backend() {}

func (*UserServiceConfig_Mysql) isUserServiceConfig_Backend() {}

// Address is a nested message type for demonstrating recursive deserializers
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	ZipCode       string                 `protobuf:"bytes,4,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_examples_simple_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simple_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_examples_simple_example_proto_rawDescGZIP(), []int{4}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// User message definition
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Address       *Address               `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"` // Nested address field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_examples_simple_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simple_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_examples_simple_example_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// Request to get a user by ID
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_examples_simple_example_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simple_example_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_examples_simple_example_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Request to create a new user
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Address       *Address               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` // Nested address - demonstrates recursive deserializers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_examples_simple_example_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simple_example_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_examples_simple_example_proto_rawDescGZIP(), []int{7}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// Response containing a user
type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_examples_simple_example_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simple_example_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_examples_simple_example_proto_rawDescGZIP(), []int{8}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_examples_simple_example_proto protoreflect.FileDescriptor

const file_examples_simple_example_proto_rawDesc = "" +
	"\n" +
	"\x1dexamples/simple/example.proto\x12\aexample\x1a\x18internal/clipb/cli.proto\"\xfb\x01\n" +
	"\x0eDatabaseConfig\x124\n" +
	"\x03url\x18\x01 \x01(\tB\"\x92\xb5\x18\x1e\n" +
	"\x03url\x1a\x17Database connection URLR\x03url\x12\\\n" +
	"\x0fmax_connections\x18\x02 \x01(\x05B3\x92\xb5\x18/\n" +
	"\x0fmax-connections\x1a\x1cMaximum database connectionsR\x0emaxConnections\x12U\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05B,\x92\xb5\x18(\n" +
	"\atimeout\x1a\x1dConnection timeout in secondsR\x0etimeoutSeconds\"U\n" +
	"\x0fPostgresBackend\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\"q\n" +
	"\fMySQLBackend\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x1d\n" +
	"\n" +
	"enable_ssl\x18\x04 \x01(\bR\tenableSsl\"\xc2\x05\n" +
	"\x11UserServiceConfig\x12L\n" +
	"\fdatabase_url\x18\x01 \x01(\tB)\x92\xb5\x18%\n" +
	"\x06db-url\x1a\x19PostgreSQL connection URL \x01R\vdatabaseUrl\x12V\n" +
	"\x0fmax_connections\x18\x02 \x01(\x03B-\x92\xb5\x18)\n" +
	"\tmax-conns\x1a\x1cMaximum database connectionsR\x0emaxConnections\x12[\n" +
	"\bdatabase\x18\x03 \x01(\v2\x17.example.DatabaseConfigB&\x92\xb5\x18\"\n" +
	"\bdatabase\x1a\x16Database configurationR\bdatabase\x12N\n" +
	"\tlog_level\x18\x04 \x01(\x0e2\x11.example.LogLevelB\x1e\x92\xb5\x18\x1a\n" +
	"\tlog-level\x1a\rLogging levelR\blogLevel\x12T\n" +
	"\x0fallowed_origins\x18\x05 \x03(\tB+\x92\xb5\x18'\n" +
	"\x0fallowed-origins\x1a\x14CORS allowed originsR\x0eallowedOrigins\x12Q\n" +
	"\rfeature_flags\x18\x06 \x03(\v2,.example.UserServiceConfig.FeatureFlagsEntryR\ffeatureFlags\x126\n" +
	"\bpostgres\x18\a \x01(\v2\x18.example.PostgresBackendH\x00R\bpostgres\x12-\n" +
	"\x05mysql\x18\b \x01(\v2\x15.example.MySQLBackendH\x00R\x05mysql\x1a?\n" +
	"\x11FeatureFlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\abackend\"\x80\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x19\n" +
	"\bzip_code\x18\x04 \x01(\tR\azipCode\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\"\x8b\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12*\n" +
	"\aaddress\x18\x05 \x01(\v2\x10.example.AddressR\aaddress\"D\n" +
	"\x0eGetUserRequest\x122\n" +
	"\x02id\x18\x01 \x01(\x03B\"\x92\xb5\x18\x1e\n" +
	"\x02id\x12\x01i\x1a\x13User ID to retrieve \x01R\x02id\"\xb4\x01\n" +
	"\x11CreateUserRequest\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\x92\xb5\x18\x1d\n" +
	"\x04name\x12\x01n\x1a\x10User's full name \x01R\x04name\x12<\n" +
	"\x05email\x18\x02 \x01(\tB&\x92\xb5\x18\"\n" +
	"\x05email\x12\x01e\x1a\x14User's email address \x01R\x05email\x12*\n" +
	"\aaddress\x18\x03 \x01(\v2\x10.example.AddressR\aaddress\"K\n" +
	"\fUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.example.UserR\x04user\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*O\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DEBUG\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\x12\b\n" +
	"\x04WARN\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x042\xd4\x02\n" +
	"\vUserService\x12a\n" +
	"\aGetUser\x12\x17.example.GetUserRequest\x1a\x15.example.UserResponse\"&\x8a\xb5\x18\"\n" +
	"\x04user\n" +
	"\x03get\x12\x15Retrieve a user by ID\x12f\n" +
	"\n" +
	"CreateUser\x12\x1a.example.CreateUserRequest\x1a\x15.example.UserResponse\"%\x8a\xb5\x18!\n" +
	"\x04user\n" +
	"\x06create\x12\x11Create a new user\x12a\n" +
	"\tListUsers\x12\x17.example.GetUserRequest\x1a\x15.example.UserResponse\" \x8a\xb5\x18\x1c\n" +
	"\x04user\n" +
	"\x04list\x12\x0eList all users(\x010\x01\x1a\x17\x9a\xb5\x18\x13\n" +
	"\x11UserServiceConfigB\x86\x01\n" +
	"\vcom.exampleB\fExampleProtoP\x01Z-github.com/drewfead/proto-cli/examples/simple\xa2\x02\x03EXX\xaa\x02\aExample\xca\x02\aExample\xe2\x02\x13Example\\GPBMetadata\xea\x02\aExampleb\x06proto3"

var (
	file_examples_simple_example_proto_rawDescOnce sync.Once
	file_examples_simple_example_proto_rawDescData []byte
)

func file_examples_simple_example_proto_rawDescGZIP() []byte {
	file_examples_simple_example_proto_rawDescOnce.Do(func() {
		file_examples_simple_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_simple_example_proto_rawDesc), len(file_examples_simple_example_proto_rawDesc)))
	})
	return file_examples_simple_example_proto_rawDescData
}

var file_examples_simple_example_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_examples_simple_example_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_examples_simple_example_proto_goTypes = []any{
	(LogLevel)(0),             // 0: example.LogLevel
	(*DatabaseConfig)(nil),    // 1: example.DatabaseConfig
	(*PostgresBackend)(nil),   // 2: example.PostgresBackend
	(*MySQLBackend)(nil),      // 3: example.MySQLBackend
	(*UserServiceConfig)(nil), // 4: example.UserServiceConfig
	(*Address)(nil),           // 5: example.Address
	(*User)(nil),              // 6: example.User
	(*GetUserRequest)(nil),    // 7: example.GetUserRequest
	(*CreateUserRequest)(nil), // 8: example.CreateUserRequest
	(*UserResponse)(nil),      // 9: example.UserResponse
	nil,                       // 10: example.UserServiceConfig.FeatureFlagsEntry
}
var file_examples_simple_example_proto_depIdxs = []int32{
	1,  // 0: example.UserServiceConfig.database:type_name -> example.DatabaseConfig
	0,  // 1: example.UserServiceConfig.log_level:type_name -> example.LogLevel
	10, // 2: example.UserServiceConfig.feature_flags:type_name -> example.UserServiceConfig.FeatureFlagsEntry
	2,  // 3: example.UserServiceConfig.postgres:type_name -> example.PostgresBackend
	3,  // 4: example.UserServiceConfig.mysql:type_name -> example.MySQLBackend
	5,  // 5: example.User.address:type_name -> example.Address
	5,  // 6: example.CreateUserRequest.address:type_name -> example.Address
	6,  // 7: example.UserResponse.user:type_name -> example.User
	7,  // 8: example.UserService.GetUser:input_type -> example.GetUserRequest
	8,  // 9: example.UserService.CreateUser:input_type -> example.CreateUserRequest
	7,  // 10: example.UserService.ListUsers:input_type -> example.GetUserRequest
	9,  // 11: example.UserService.GetUser:output_type -> example.UserResponse
	9,  // 12: example.UserService.CreateUser:output_type -> example.UserResponse
	9,  // 13: example.UserService.ListUsers:output_type -> example.UserResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_examples_simple_example_proto_init() }
func file_examples_simple_example_proto_init() {
	if File_examples_simple_example_proto != nil {
		return
	}
	file_examples_simple_example_proto_msgTypes[3].OneofWrappers = []any{
		(*UserServiceConfig_Postgres)(nil),
		(*UserServiceConfig_Mysql)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_simple_example_proto_rawDesc), len(file_examples_simple_example_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_simple_example_proto_goTypes,
		DependencyIndexes: file_examples_simple_example_proto_depIdxs,
		EnumInfos:         file_examples_simple_example_proto_enumTypes,
		MessageInfos:      file_examples_simple_example_proto_msgTypes,
	}.Build()
	File_examples_simple_example_proto = out.File
	file_examples_simple_example_proto_goTypes = nil
	file_examples_simple_example_proto_depIdxs = nil
}
