// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: examples/simple/override_test.proto

package simple

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestOverrideService_CustomCommand_FullMethodName           = "/example.TestOverrideService/CustomCommand"
	TestOverrideService_DefaultKebabCaseCommand_FullMethodName = "/example.TestOverrideService/DefaultKebabCaseCommand"
)

// TestOverrideServiceClient is the client API for TestOverrideService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TestOverrideService demonstrates service name and description overrides
type TestOverrideServiceClient interface {
	// Command with custom name and description
	CustomCommand(ctx context.Context, in *TestOverrideRequest, opts ...grpc.CallOption) (*TestOverrideResponse, error)
	// Command using default kebab-case
	DefaultKebabCaseCommand(ctx context.Context, in *TestOverrideRequest, opts ...grpc.CallOption) (*TestOverrideResponse, error)
}

type testOverrideServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestOverrideServiceClient(cc grpc.ClientConnInterface) TestOverrideServiceClient {
	return &testOverrideServiceClient{cc}
}

func (c *testOverrideServiceClient) CustomCommand(ctx context.Context, in *TestOverrideRequest, opts ...grpc.CallOption) (*TestOverrideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestOverrideResponse)
	err := c.cc.Invoke(ctx, TestOverrideService_CustomCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testOverrideServiceClient) DefaultKebabCaseCommand(ctx context.Context, in *TestOverrideRequest, opts ...grpc.CallOption) (*TestOverrideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestOverrideResponse)
	err := c.cc.Invoke(ctx, TestOverrideService_DefaultKebabCaseCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestOverrideServiceServer is the server API for TestOverrideService service.
// All implementations must embed UnimplementedTestOverrideServiceServer
// for forward compatibility.
//
// TestOverrideService demonstrates service name and description overrides
type TestOverrideServiceServer interface {
	// Command with custom name and description
	CustomCommand(context.Context, *TestOverrideRequest) (*TestOverrideResponse, error)
	// Command using default kebab-case
	DefaultKebabCaseCommand(context.Context, *TestOverrideRequest) (*TestOverrideResponse, error)
	mustEmbedUnimplementedTestOverrideServiceServer()
}

// UnimplementedTestOverrideServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestOverrideServiceServer struct{}

func (UnimplementedTestOverrideServiceServer) CustomCommand(context.Context, *TestOverrideRequest) (*TestOverrideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CustomCommand not implemented")
}

func (UnimplementedTestOverrideServiceServer) DefaultKebabCaseCommand(context.Context, *TestOverrideRequest) (*TestOverrideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DefaultKebabCaseCommand not implemented")
}
func (UnimplementedTestOverrideServiceServer) mustEmbedUnimplementedTestOverrideServiceServer() {}
func (UnimplementedTestOverrideServiceServer) testEmbeddedByValue()                             {}

// UnsafeTestOverrideServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestOverrideServiceServer will
// result in compilation errors.
type UnsafeTestOverrideServiceServer interface {
	mustEmbedUnimplementedTestOverrideServiceServer()
}

func RegisterTestOverrideServiceServer(s grpc.ServiceRegistrar, srv TestOverrideServiceServer) {
	// If the following call panics, it indicates UnimplementedTestOverrideServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestOverrideService_ServiceDesc, srv)
}

func _TestOverrideService_CustomCommand_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(TestOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestOverrideServiceServer).CustomCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestOverrideService_CustomCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(TestOverrideServiceServer).CustomCommand(ctx, req.(*TestOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestOverrideService_DefaultKebabCaseCommand_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(TestOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestOverrideServiceServer).DefaultKebabCaseCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestOverrideService_DefaultKebabCaseCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(TestOverrideServiceServer).DefaultKebabCaseCommand(ctx, req.(*TestOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TestOverrideService_ServiceDesc is the grpc.ServiceDesc for TestOverrideService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestOverrideService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.TestOverrideService",
	HandlerType: (*TestOverrideServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CustomCommand",
			Handler:    _TestOverrideService_CustomCommand_Handler,
		},
		{
			MethodName: "DefaultKebabCaseCommand",
			Handler:    _TestOverrideService_DefaultKebabCaseCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/simple/override_test.proto",
}

const (
	DefaultKebabCaseService_AnotherTestCommand_FullMethodName = "/example.DefaultKebabCaseService/AnotherTestCommand"
)

// DefaultKebabCaseServiceClient is the client API for DefaultKebabCaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DefaultKebabCaseService demonstrates default naming
type DefaultKebabCaseServiceClient interface {
	AnotherTestCommand(ctx context.Context, in *TestOverrideRequest, opts ...grpc.CallOption) (*TestOverrideResponse, error)
}

type defaultKebabCaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDefaultKebabCaseServiceClient(cc grpc.ClientConnInterface) DefaultKebabCaseServiceClient {
	return &defaultKebabCaseServiceClient{cc}
}

func (c *defaultKebabCaseServiceClient) AnotherTestCommand(ctx context.Context, in *TestOverrideRequest, opts ...grpc.CallOption) (*TestOverrideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestOverrideResponse)
	err := c.cc.Invoke(ctx, DefaultKebabCaseService_AnotherTestCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DefaultKebabCaseServiceServer is the server API for DefaultKebabCaseService service.
// All implementations must embed UnimplementedDefaultKebabCaseServiceServer
// for forward compatibility.
//
// DefaultKebabCaseService demonstrates default naming
type DefaultKebabCaseServiceServer interface {
	AnotherTestCommand(context.Context, *TestOverrideRequest) (*TestOverrideResponse, error)
	mustEmbedUnimplementedDefaultKebabCaseServiceServer()
}

// UnimplementedDefaultKebabCaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDefaultKebabCaseServiceServer struct{}

func (UnimplementedDefaultKebabCaseServiceServer) AnotherTestCommand(context.Context, *TestOverrideRequest) (*TestOverrideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnotherTestCommand not implemented")
}

func (UnimplementedDefaultKebabCaseServiceServer) mustEmbedUnimplementedDefaultKebabCaseServiceServer() {
}
func (UnimplementedDefaultKebabCaseServiceServer) testEmbeddedByValue() {}

// UnsafeDefaultKebabCaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DefaultKebabCaseServiceServer will
// result in compilation errors.
type UnsafeDefaultKebabCaseServiceServer interface {
	mustEmbedUnimplementedDefaultKebabCaseServiceServer()
}

func RegisterDefaultKebabCaseServiceServer(s grpc.ServiceRegistrar, srv DefaultKebabCaseServiceServer) {
	// If the following call panics, it indicates UnimplementedDefaultKebabCaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DefaultKebabCaseService_ServiceDesc, srv)
}

func _DefaultKebabCaseService_AnotherTestCommand_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(TestOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultKebabCaseServiceServer).AnotherTestCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DefaultKebabCaseService_AnotherTestCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(DefaultKebabCaseServiceServer).AnotherTestCommand(ctx, req.(*TestOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DefaultKebabCaseService_ServiceDesc is the grpc.ServiceDesc for DefaultKebabCaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DefaultKebabCaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.DefaultKebabCaseService",
	HandlerType: (*DefaultKebabCaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnotherTestCommand",
			Handler:    _DefaultKebabCaseService_AnotherTestCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/simple/override_test.proto",
}
