// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: examples/simple/override_test.proto

package simple

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/drewfead/proto-cli/internal/clipb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TestOverride demonstrates all CLI annotation overrides
type TestOverrideRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This field will use custom flag name
	CustomFlag string `protobuf:"bytes,1,opt,name=custom_flag,json=customFlag,proto3" json:"custom_flag,omitempty"`
	// This field will use default kebab-case: default-kebab-case-flag
	DefaultKebabCaseFlag string `protobuf:"bytes,2,opt,name=DefaultKebabCaseFlag,proto3" json:"DefaultKebabCaseFlag,omitempty"`
	// This field will use explicit name
	AnotherField  string `protobuf:"bytes,3,opt,name=AnotherField,proto3" json:"AnotherField,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestOverrideRequest) Reset() {
	*x = TestOverrideRequest{}
	mi := &file_examples_simple_override_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOverrideRequest) ProtoMessage() {}

func (x *TestOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simple_override_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOverrideRequest.ProtoReflect.Descriptor instead.
func (*TestOverrideRequest) Descriptor() ([]byte, []int) {
	return file_examples_simple_override_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestOverrideRequest) GetCustomFlag() string {
	if x != nil {
		return x.CustomFlag
	}
	return ""
}

func (x *TestOverrideRequest) GetDefaultKebabCaseFlag() string {
	if x != nil {
		return x.DefaultKebabCaseFlag
	}
	return ""
}

func (x *TestOverrideRequest) GetAnotherField() string {
	if x != nil {
		return x.AnotherField
	}
	return ""
}

type TestOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestOverrideResponse) Reset() {
	*x = TestOverrideResponse{}
	mi := &file_examples_simple_override_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOverrideResponse) ProtoMessage() {}

func (x *TestOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simple_override_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOverrideResponse.ProtoReflect.Descriptor instead.
func (*TestOverrideResponse) Descriptor() ([]byte, []int) {
	return file_examples_simple_override_test_proto_rawDescGZIP(), []int{1}
}

func (x *TestOverrideResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_examples_simple_override_test_proto protoreflect.FileDescriptor

const file_examples_simple_override_test_proto_rawDesc = "" +
	"\n" +
	"#examples/simple/override_test.proto\x12\aexample\x1a\x18internal/clipb/cli.proto\"\xed\x01\n" +
	"\x13TestOverrideRequest\x12R\n" +
	"\vcustom_flag\x18\x01 \x01(\tB1\x92\xb5\x18-\n" +
	"\x0emy-custom-flag\x1a\x1bA custom flag name overrideR\n" +
	"customFlag\x122\n" +
	"\x14DefaultKebabCaseFlag\x18\x02 \x01(\tR\x14DefaultKebabCaseFlag\x12N\n" +
	"\fAnotherField\x18\x03 \x01(\tB*\x92\xb5\x18&\n" +
	"\rexplicit-name\x1a\x15Explicitly named flagR\fAnotherField\"0\n" +
	"\x14TestOverrideResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa7\x02\n" +
	"\x13TestOverrideService\x12\x81\x01\n" +
	"\rCustomCommand\x12\x1c.example.TestOverrideRequest\x1a\x1d.example.TestOverrideResponse\"3\x8a\xb5\x18/\n" +
	"\x02my\n" +
	"\x06custom\n" +
	"\x03cmd\x12\x1cA custom command description\x12X\n" +
	"\x17DefaultKebabCaseCommand\x12\x1c.example.TestOverrideRequest\x1a\x1d.example.TestOverrideResponse\"\x00\x1a2\x82\xb5\x18.\n" +
	"\x0ecustom-service\x12\x1cA custom service description2n\n" +
	"\x17DefaultKebabCaseService\x12S\n" +
	"\x12AnotherTestCommand\x12\x1c.example.TestOverrideRequest\x1a\x1d.example.TestOverrideResponse\"\x00B\x8b\x01\n" +
	"\vcom.exampleB\x11OverrideTestProtoP\x01Z-github.com/drewfead/proto-cli/examples/simple\xa2\x02\x03EXX\xaa\x02\aExample\xca\x02\aExample\xe2\x02\x13Example\\GPBMetadata\xea\x02\aExampleb\x06proto3"

var (
	file_examples_simple_override_test_proto_rawDescOnce sync.Once
	file_examples_simple_override_test_proto_rawDescData []byte
)

func file_examples_simple_override_test_proto_rawDescGZIP() []byte {
	file_examples_simple_override_test_proto_rawDescOnce.Do(func() {
		file_examples_simple_override_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_simple_override_test_proto_rawDesc), len(file_examples_simple_override_test_proto_rawDesc)))
	})
	return file_examples_simple_override_test_proto_rawDescData
}

var file_examples_simple_override_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_simple_override_test_proto_goTypes = []any{
	(*TestOverrideRequest)(nil),  // 0: example.TestOverrideRequest
	(*TestOverrideResponse)(nil), // 1: example.TestOverrideResponse
}
var file_examples_simple_override_test_proto_depIdxs = []int32{
	0, // 0: example.TestOverrideService.CustomCommand:input_type -> example.TestOverrideRequest
	0, // 1: example.TestOverrideService.DefaultKebabCaseCommand:input_type -> example.TestOverrideRequest
	0, // 2: example.DefaultKebabCaseService.AnotherTestCommand:input_type -> example.TestOverrideRequest
	1, // 3: example.TestOverrideService.CustomCommand:output_type -> example.TestOverrideResponse
	1, // 4: example.TestOverrideService.DefaultKebabCaseCommand:output_type -> example.TestOverrideResponse
	1, // 5: example.DefaultKebabCaseService.AnotherTestCommand:output_type -> example.TestOverrideResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_simple_override_test_proto_init() }
func file_examples_simple_override_test_proto_init() {
	if File_examples_simple_override_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_simple_override_test_proto_rawDesc), len(file_examples_simple_override_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_examples_simple_override_test_proto_goTypes,
		DependencyIndexes: file_examples_simple_override_test_proto_depIdxs,
		MessageInfos:      file_examples_simple_override_test_proto_msgTypes,
	}.Build()
	File_examples_simple_override_test_proto = out.File
	file_examples_simple_override_test_proto_goTypes = nil
	file_examples_simple_override_test_proto_depIdxs = nil
}
