// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/clipb/cli.proto

package clipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CLI command annotation for RPC methods
// Defines the command hierarchy (e.g., ["user", "get"] -> "mycli user get")
type CommandOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOptions) Reset() {
	*x = CommandOptions{}
	mi := &file_internal_clipb_cli_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOptions) ProtoMessage() {}

func (x *CommandOptions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clipb_cli_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOptions.ProtoReflect.Descriptor instead.
func (*CommandOptions) Descriptor() ([]byte, []int) {
	return file_internal_clipb_cli_proto_rawDescGZIP(), []int{0}
}

func (x *CommandOptions) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CLI flag annotation for message fields
// Maps message fields to CLI flags
type FlagOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shorthand     string                 `protobuf:"bytes,2,opt,name=shorthand,proto3" json:"shorthand,omitempty"`
	Usage         string                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagOptions) Reset() {
	*x = FlagOptions{}
	mi := &file_internal_clipb_cli_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagOptions) ProtoMessage() {}

func (x *FlagOptions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clipb_cli_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagOptions.ProtoReflect.Descriptor instead.
func (*FlagOptions) Descriptor() ([]byte, []int) {
	return file_internal_clipb_cli_proto_rawDescGZIP(), []int{1}
}

func (x *FlagOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlagOptions) GetShorthand() string {
	if x != nil {
		return x.Shorthand
	}
	return ""
}

func (x *FlagOptions) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *FlagOptions) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

// Service config annotation
// Defines the configuration message type for a service
type ServiceConfigOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the config message type (must be in same package)
	ConfigMessage string `protobuf:"bytes,1,opt,name=config_message,json=configMessage,proto3" json:"config_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfigOptions) Reset() {
	*x = ServiceConfigOptions{}
	mi := &file_internal_clipb_cli_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfigOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfigOptions) ProtoMessage() {}

func (x *ServiceConfigOptions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_clipb_cli_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfigOptions.ProtoReflect.Descriptor instead.
func (*ServiceConfigOptions) Descriptor() ([]byte, []int) {
	return file_internal_clipb_cli_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceConfigOptions) GetConfigMessage() string {
	if x != nil {
		return x.ConfigMessage
	}
	return ""
}

var file_internal_clipb_cli_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*CommandOptions)(nil),
		Field:         50001,
		Name:          "cli.command",
		Tag:           "bytes,50001,opt,name=command",
		Filename:      "internal/clipb/cli.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FlagOptions)(nil),
		Field:         50002,
		Name:          "cli.flag",
		Tag:           "bytes,50002,opt,name=flag",
		Filename:      "internal/clipb/cli.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceConfigOptions)(nil),
		Field:         50003,
		Name:          "cli.service_config",
		Tag:           "bytes,50003,opt,name=service_config",
		Filename:      "internal/clipb/cli.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional cli.CommandOptions command = 50001;
	E_Command = &file_internal_clipb_cli_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional cli.FlagOptions flag = 50002;
	E_Flag = &file_internal_clipb_cli_proto_extTypes[1]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional cli.ServiceConfigOptions service_config = 50003;
	E_ServiceConfig = &file_internal_clipb_cli_proto_extTypes[2]
)

var File_internal_clipb_cli_proto protoreflect.FileDescriptor

const file_internal_clipb_cli_proto_rawDesc = "" +
	"\n" +
	"\x18internal/clipb/cli.proto\x12\x03cli\x1a google/protobuf/descriptor.proto\"L\n" +
	"\x0eCommandOptions\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"q\n" +
	"\vFlagOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tshorthand\x18\x02 \x01(\tR\tshorthand\x12\x14\n" +
	"\x05usage\x18\x03 \x01(\tR\x05usage\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\"=\n" +
	"\x14ServiceConfigOptions\x12%\n" +
	"\x0econfig_message\x18\x01 \x01(\tR\rconfigMessage:O\n" +
	"\acommand\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\v2\x13.cli.CommandOptionsR\acommand:E\n" +
	"\x04flag\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\v2\x10.cli.FlagOptionsR\x04flag:c\n" +
	"\x0eservice_config\x12\x1f.google.protobuf.ServiceOptions\x18ӆ\x03 \x01(\v2\x19.cli.ServiceConfigOptionsR\rserviceConfigBm\n" +
	"\acom.cliB\bCliProtoP\x01Z,github.com/drewfead/proto-cli/internal/clipb\xa2\x02\x03CXX\xaa\x02\x03Cli\xca\x02\x03Cli\xe2\x02\x0fCli\\GPBMetadata\xea\x02\x03Clib\x06proto3"

var (
	file_internal_clipb_cli_proto_rawDescOnce sync.Once
	file_internal_clipb_cli_proto_rawDescData []byte
)

func file_internal_clipb_cli_proto_rawDescGZIP() []byte {
	file_internal_clipb_cli_proto_rawDescOnce.Do(func() {
		file_internal_clipb_cli_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_clipb_cli_proto_rawDesc), len(file_internal_clipb_cli_proto_rawDesc)))
	})
	return file_internal_clipb_cli_proto_rawDescData
}

var file_internal_clipb_cli_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_clipb_cli_proto_goTypes = []any{
	(*CommandOptions)(nil),              // 0: cli.CommandOptions
	(*FlagOptions)(nil),                 // 1: cli.FlagOptions
	(*ServiceConfigOptions)(nil),        // 2: cli.ServiceConfigOptions
	(*descriptorpb.MethodOptions)(nil),  // 3: google.protobuf.MethodOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
	(*descriptorpb.ServiceOptions)(nil), // 5: google.protobuf.ServiceOptions
}
var file_internal_clipb_cli_proto_depIdxs = []int32{
	3, // 0: cli.command:extendee -> google.protobuf.MethodOptions
	4, // 1: cli.flag:extendee -> google.protobuf.FieldOptions
	5, // 2: cli.service_config:extendee -> google.protobuf.ServiceOptions
	0, // 3: cli.command:type_name -> cli.CommandOptions
	1, // 4: cli.flag:type_name -> cli.FlagOptions
	2, // 5: cli.service_config:type_name -> cli.ServiceConfigOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	3, // [3:6] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_clipb_cli_proto_init() }
func file_internal_clipb_cli_proto_init() {
	if File_internal_clipb_cli_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_clipb_cli_proto_rawDesc), len(file_internal_clipb_cli_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_internal_clipb_cli_proto_goTypes,
		DependencyIndexes: file_internal_clipb_cli_proto_depIdxs,
		MessageInfos:      file_internal_clipb_cli_proto_msgTypes,
		ExtensionInfos:    file_internal_clipb_cli_proto_extTypes,
	}.Build()
	File_internal_clipb_cli_proto = out.File
	file_internal_clipb_cli_proto_goTypes = nil
	file_internal_clipb_cli_proto_depIdxs = nil
}
