// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: examples/tui/tui.proto

package tui

import (
	_ "github.com/drewfead/proto-cli/proto/cli/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GreetRequest asks for a greeting.
type GreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Repeat        int32                  `protobuf:"varint,2,opt,name=repeat,proto3" json:"repeat,omitempty"`
	Loud          bool                   `protobuf:"varint,3,opt,name=loud,proto3" json:"loud,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_examples_tui_tui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GreetRequest) GetRepeat() int32 {
	if x != nil {
		return x.Repeat
	}
	return 0
}

func (x *GreetRequest) GetLoud() bool {
	if x != nil {
		return x.Loud
	}
	return false
}

// GreetResponse contains the greeting.
type GreetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetResponse) Reset() {
	*x = GreetResponse{}
	mi := &file_examples_tui_tui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponse) ProtoMessage() {}

func (x *GreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponse.ProtoReflect.Descriptor instead.
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{1}
}

func (x *GreetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ListGreetingsRequest asks for a list of greetings.
type ListGreetingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGreetingsRequest) Reset() {
	*x = ListGreetingsRequest{}
	mi := &file_examples_tui_tui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGreetingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGreetingsRequest) ProtoMessage() {}

func (x *ListGreetingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGreetingsRequest.ProtoReflect.Descriptor instead.
func (*ListGreetingsRequest) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{2}
}

func (x *ListGreetingsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// ListGreetingsResponse contains a list of greetings.
type ListGreetingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []string               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGreetingsResponse) Reset() {
	*x = ListGreetingsResponse{}
	mi := &file_examples_tui_tui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGreetingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGreetingsResponse) ProtoMessage() {}

func (x *ListGreetingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGreetingsResponse.ProtoReflect.Descriptor instead.
func (*ListGreetingsResponse) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{3}
}

func (x *ListGreetingsResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

// FarewellRequest asks for a farewell.
type FarewellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Formal        bool                   `protobuf:"varint,2,opt,name=formal,proto3" json:"formal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarewellRequest) Reset() {
	*x = FarewellRequest{}
	mi := &file_examples_tui_tui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarewellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarewellRequest) ProtoMessage() {}

func (x *FarewellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarewellRequest.ProtoReflect.Descriptor instead.
func (*FarewellRequest) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{4}
}

func (x *FarewellRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FarewellRequest) GetFormal() bool {
	if x != nil {
		return x.Formal
	}
	return false
}

// FarewellResponse contains the farewell message.
type FarewellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarewellResponse) Reset() {
	*x = FarewellResponse{}
	mi := &file_examples_tui_tui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarewellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarewellResponse) ProtoMessage() {}

func (x *FarewellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarewellResponse.ProtoReflect.Descriptor instead.
func (*FarewellResponse) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{5}
}

func (x *FarewellResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// FarewellManyRequest asks for farewells to multiple people.
type FarewellManyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarewellManyRequest) Reset() {
	*x = FarewellManyRequest{}
	mi := &file_examples_tui_tui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarewellManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarewellManyRequest) ProtoMessage() {}

func (x *FarewellManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarewellManyRequest.ProtoReflect.Descriptor instead.
func (*FarewellManyRequest) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{6}
}

func (x *FarewellManyRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

// FarewellManyResponse contains a list of farewell messages.
type FarewellManyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []string               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FarewellManyResponse) Reset() {
	*x = FarewellManyResponse{}
	mi := &file_examples_tui_tui_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FarewellManyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FarewellManyResponse) ProtoMessage() {}

func (x *FarewellManyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FarewellManyResponse.ProtoReflect.Descriptor instead.
func (*FarewellManyResponse) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{7}
}

func (x *FarewellManyResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

// CountdownFarewellRequest asks for a dramatic countdown farewell.
type CountdownFarewellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	From          int32                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	DelayMs       int32                  `protobuf:"varint,3,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountdownFarewellRequest) Reset() {
	*x = CountdownFarewellRequest{}
	mi := &file_examples_tui_tui_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountdownFarewellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountdownFarewellRequest) ProtoMessage() {}

func (x *CountdownFarewellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountdownFarewellRequest.ProtoReflect.Descriptor instead.
func (*CountdownFarewellRequest) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{8}
}

func (x *CountdownFarewellRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CountdownFarewellRequest) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *CountdownFarewellRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

// CountdownFarewellResponse carries one tick of the countdown, or the
// final farewell message when the count reaches zero.
type CountdownFarewellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountdownFarewellResponse) Reset() {
	*x = CountdownFarewellResponse{}
	mi := &file_examples_tui_tui_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountdownFarewellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountdownFarewellResponse) ProtoMessage() {}

func (x *CountdownFarewellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountdownFarewellResponse.ProtoReflect.Descriptor instead.
func (*CountdownFarewellResponse) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{9}
}

func (x *CountdownFarewellResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeliveryAddress holds a postal address, used to demonstrate nested message flattening in the TUI.
type DeliveryAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryAddress) Reset() {
	*x = DeliveryAddress{}
	mi := &file_examples_tui_tui_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAddress) ProtoMessage() {}

func (x *DeliveryAddress) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAddress.ProtoReflect.Descriptor instead.
func (*DeliveryAddress) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{10}
}

func (x *DeliveryAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *DeliveryAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

// ScheduledFarewellRequest asks for a farewell at a specific time, delivered to an address.
// Demonstrates WKT (Timestamp) and nested message flattening.
type ScheduledFarewellRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// send_at is when to deliver the farewell. Demonstrates google.protobuf.Timestamp WKT support.
	SendAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
	// address is where to deliver the farewell. Demonstrates nested message flattening in the TUI.
	Address       *DeliveryAddress `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduledFarewellRequest) Reset() {
	*x = ScheduledFarewellRequest{}
	mi := &file_examples_tui_tui_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledFarewellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledFarewellRequest) ProtoMessage() {}

func (x *ScheduledFarewellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledFarewellRequest.ProtoReflect.Descriptor instead.
func (*ScheduledFarewellRequest) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{11}
}

func (x *ScheduledFarewellRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScheduledFarewellRequest) GetSendAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SendAt
	}
	return nil
}

func (x *ScheduledFarewellRequest) GetAddress() *DeliveryAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

// ScheduledFarewellResponse contains the scheduled farewell.
type ScheduledFarewellResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ScheduledFor    string                 `protobuf:"bytes,2,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	DeliveryAddress string                 `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScheduledFarewellResponse) Reset() {
	*x = ScheduledFarewellResponse{}
	mi := &file_examples_tui_tui_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledFarewellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledFarewellResponse) ProtoMessage() {}

func (x *ScheduledFarewellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledFarewellResponse.ProtoReflect.Descriptor instead.
func (*ScheduledFarewellResponse) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{12}
}

func (x *ScheduledFarewellResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScheduledFarewellResponse) GetScheduledFor() string {
	if x != nil {
		return x.ScheduledFor
	}
	return ""
}

func (x *ScheduledFarewellResponse) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

// RgbColor holds an RGB color value. Used to demonstrate custom TUI form controls.
type RgbColor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             int32                  `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	G             int32                  `protobuf:"varint,2,opt,name=g,proto3" json:"g,omitempty"`
	B             int32                  `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RgbColor) Reset() {
	*x = RgbColor{}
	mi := &file_examples_tui_tui_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RgbColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RgbColor) ProtoMessage() {}

func (x *RgbColor) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RgbColor.ProtoReflect.Descriptor instead.
func (*RgbColor) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{13}
}

func (x *RgbColor) GetR() int32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *RgbColor) GetG() int32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *RgbColor) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

// ColoredGreetRequest asks for a greeting rendered in a chosen color.
// Demonstrates registering a custom TUI form control for RgbColor.
type ColoredGreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color         *RgbColor              `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColoredGreetRequest) Reset() {
	*x = ColoredGreetRequest{}
	mi := &file_examples_tui_tui_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColoredGreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColoredGreetRequest) ProtoMessage() {}

func (x *ColoredGreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColoredGreetRequest.ProtoReflect.Descriptor instead.
func (*ColoredGreetRequest) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{14}
}

func (x *ColoredGreetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColoredGreetRequest) GetColor() *RgbColor {
	if x != nil {
		return x.Color
	}
	return nil
}

// ColoredGreetResponse contains the greeting along with a hex color code.
type ColoredGreetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ColorHex      string                 `protobuf:"bytes,2,opt,name=color_hex,json=colorHex,proto3" json:"color_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColoredGreetResponse) Reset() {
	*x = ColoredGreetResponse{}
	mi := &file_examples_tui_tui_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColoredGreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColoredGreetResponse) ProtoMessage() {}

func (x *ColoredGreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColoredGreetResponse.ProtoReflect.Descriptor instead.
func (*ColoredGreetResponse) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{15}
}

func (x *ColoredGreetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ColoredGreetResponse) GetColorHex() string {
	if x != nil {
		return x.ColorHex
	}
	return ""
}

// NoteRequest demonstrates a freeform JSON editor TUI control.
type NoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// metadata is free-form JSON attached to the note.
	// In the TUI this field uses the JSON editor control.
	Metadata      string `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteRequest) Reset() {
	*x = NoteRequest{}
	mi := &file_examples_tui_tui_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteRequest) ProtoMessage() {}

func (x *NoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteRequest.ProtoReflect.Descriptor instead.
func (*NoteRequest) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{16}
}

func (x *NoteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NoteRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

// NoteResponse contains the echoed note.
type NoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      string                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteResponse) Reset() {
	*x = NoteResponse{}
	mi := &file_examples_tui_tui_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteResponse) ProtoMessage() {}

func (x *NoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteResponse.ProtoReflect.Descriptor instead.
func (*NoteResponse) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{17}
}

func (x *NoteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NoteResponse) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

// ScheduleCallRequest books a call at a user-supplied time.
// The `when` field is a google.protobuf.Timestamp. The TUI picker accepts
// the time in the system's local timezone and normalises it to UTC on submit.
// Compare with ScheduledFarewell which also uses Timestamp but with UTC input.
type ScheduleCallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	With  string                 `protobuf:"bytes,1,opt,name=with,proto3" json:"with,omitempty"`
	// when is when to schedule the call. In the TUI this field is rendered as a
	// date-time picker that accepts local time (SystemTimezone) and normalises
	// to UTC for the Timestamp wire format.
	When          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=when,proto3" json:"when,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleCallRequest) Reset() {
	*x = ScheduleCallRequest{}
	mi := &file_examples_tui_tui_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleCallRequest) ProtoMessage() {}

func (x *ScheduleCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleCallRequest.ProtoReflect.Descriptor instead.
func (*ScheduleCallRequest) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{18}
}

func (x *ScheduleCallRequest) GetWith() string {
	if x != nil {
		return x.With
	}
	return ""
}

func (x *ScheduleCallRequest) GetWhen() *timestamppb.Timestamp {
	if x != nil {
		return x.When
	}
	return nil
}

// ScheduleCallResponse echoes the scheduled call time in both the server's
// local timezone and UTC, demonstrating that the TUI picker's local-time
// entry round-trips correctly through the Timestamp wire format.
type ScheduleCallResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// when_local is the call time in the server's local timezone.
	WhenLocal string `protobuf:"bytes,2,opt,name=when_local,json=whenLocal,proto3" json:"when_local,omitempty"`
	// when_utc is the same instant expressed in UTC.
	WhenUtc       string `protobuf:"bytes,3,opt,name=when_utc,json=whenUtc,proto3" json:"when_utc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleCallResponse) Reset() {
	*x = ScheduleCallResponse{}
	mi := &file_examples_tui_tui_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleCallResponse) ProtoMessage() {}

func (x *ScheduleCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleCallResponse.ProtoReflect.Descriptor instead.
func (*ScheduleCallResponse) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{19}
}

func (x *ScheduleCallResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScheduleCallResponse) GetWhenLocal() string {
	if x != nil {
		return x.WhenLocal
	}
	return ""
}

func (x *ScheduleCallResponse) GetWhenUtc() string {
	if x != nil {
		return x.WhenUtc
	}
	return ""
}

// PersonCard describes one person in the directory who can be greeted.
type PersonCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonCard) Reset() {
	*x = PersonCard{}
	mi := &file_examples_tui_tui_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonCard) ProtoMessage() {}

func (x *PersonCard) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonCard.ProtoReflect.Descriptor instead.
func (*PersonCard) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{20}
}

func (x *PersonCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonCard) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

// ListPeopleRequest asks for the list of contacts available to greet.
type ListPeopleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// filter narrows results to names starting with the given prefix.
	// Leave empty to list everyone.
	Filter        string `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeopleRequest) Reset() {
	*x = ListPeopleRequest{}
	mi := &file_examples_tui_tui_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeopleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeopleRequest) ProtoMessage() {}

func (x *ListPeopleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_tui_tui_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeopleRequest.ProtoReflect.Descriptor instead.
func (*ListPeopleRequest) Descriptor() ([]byte, []int) {
	return file_examples_tui_tui_proto_rawDescGZIP(), []int{21}
}

func (x *ListPeopleRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

var File_examples_tui_tui_proto protoreflect.FileDescriptor

const file_examples_tui_tui_proto_rawDesc = "" +
	"\n" +
	"\x16examples/tui/tui.proto\x12\vtui_example\x1a\x16proto/cli/v1/cli.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x01\n" +
	"\fGreetRequest\x12/\n" +
	"\x04name\x18\x01 \x01(\tB\x1b\x92\xb5\x18\x17\n" +
	"\x04name\x1a\rName to greet \x01R\x04name\x12O\n" +
	"\x06repeat\x18\x02 \x01(\x05B7\x92\xb5\x183\n" +
	"\x06repeat\x1a&Number of times to repeat the greetingb\x011R\x06repeat\x12H\n" +
	"\x04loud\x18\x03 \x01(\bB4\x92\xb5\x180\n" +
	"\x04loud\x1a\"Whether to greet loudly (all caps)b\x04trueR\x04loud\")\n" +
	"\rGreetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"b\n" +
	"\x14ListGreetingsRequest\x12J\n" +
	"\x05names\x18\x01 \x03(\tB4\x92\xb5\x180\n" +
	"\x05names\x1a'Names to greet (comma-separated in TUI)R\x05names\"3\n" +
	"\x15ListGreetingsResponse\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\tR\bmessages\"\x86\x01\n" +
	"\x0fFarewellRequest\x126\n" +
	"\x04name\x18\x01 \x01(\tB\"\x92\xb5\x18\x1e\n" +
	"\x04name\x1a\x14Name to bid farewell \x01R\x04name\x12;\n" +
	"\x06formal\x18\x02 \x01(\bB#\x92\xb5\x18\x1f\n" +
	"\x06formal\x1a\x15Use a formal farewellR\x06formal\",\n" +
	"\x10FarewellResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"h\n" +
	"\x13FarewellManyRequest\x12Q\n" +
	"\x05names\x18\x01 \x03(\tB;\x92\xb5\x187\n" +
	"\x05names\x1a.Names to bid farewell (comma-separated in TUI)R\x05names\"2\n" +
	"\x14FarewellManyResponse\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\tR\bmessages\"\xe6\x01\n" +
	"\x18CountdownFarewellRequest\x126\n" +
	"\x04name\x18\x01 \x01(\tB\"\x92\xb5\x18\x1e\n" +
	"\x04name\x1a\x14Name to bid farewell \x01R\x04name\x12<\n" +
	"\x04from\x18\x02 \x01(\x05B(\x92\xb5\x18$\n" +
	"\x04from\x1a\x19Countdown starting numberb\x015R\x04from\x12T\n" +
	"\bdelay_ms\x18\x03 \x01(\x05B9\x92\xb5\x185\n" +
	"\bdelay-ms\x1a$Milliseconds between countdown ticksb\x03500R\adelayMs\"5\n" +
	"\x19CountdownFarewellResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"m\n" +
	"\x0fDeliveryAddress\x124\n" +
	"\x06street\x18\x01 \x01(\tB\x1c\x92\xb5\x18\x18\n" +
	"\x06street\x1a\x0eStreet addressR\x06street\x12$\n" +
	"\x04city\x18\x02 \x01(\tB\x10\x92\xb5\x18\f\n" +
	"\x04city\x1a\x04CityR\x04city\"\x96\x02\n" +
	"\x18ScheduledFarewellRequest\x126\n" +
	"\x04name\x18\x01 \x01(\tB\"\x92\xb5\x18\x1e\n" +
	"\x04name\x1a\x14Name to bid farewell \x01R\x04name\x12g\n" +
	"\asend_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB2\x92\xb5\x18.\n" +
	"\asend-at\x1a#When to send the farewell (RFC3339)R\x06sendAt\x12Y\n" +
	"\aaddress\x18\x03 \x01(\v2\x1c.tui_example.DeliveryAddressB!\x92\xb5\x18\x1d\n" +
	"\aaddressR\x12\n" +
	"\x10Delivery AddressR\aaddress\"\x85\x01\n" +
	"\x19ScheduledFarewellResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12#\n" +
	"\rscheduled_for\x18\x02 \x01(\tR\fscheduledFor\x12)\n" +
	"\x10delivery_address\x18\x03 \x01(\tR\x0fdeliveryAddress\"\xa9\x01\n" +
	"\bRgbColor\x121\n" +
	"\x01r\x18\x01 \x01(\x05B#\x92\xb5\x18\x1f\n" +
	"\x01r\x1a\x13Red channel (0-255)R\x05\n" +
	"\x03RedR\x01r\x125\n" +
	"\x01g\x18\x02 \x01(\x05B'\x92\xb5\x18#\n" +
	"\x01g\x1a\x15Green channel (0-255)R\a\n" +
	"\x05GreenR\x01g\x123\n" +
	"\x01b\x18\x03 \x01(\x05B%\x92\xb5\x18!\n" +
	"\x01b\x1a\x14Blue channel (0-255)R\x06\n" +
	"\x04BlueR\x01b\"\xa2\x01\n" +
	"\x13ColoredGreetRequest\x12/\n" +
	"\x04name\x18\x01 \x01(\tB\x1b\x92\xb5\x18\x17\n" +
	"\x04name\x1a\rName to greet \x01R\x04name\x12Z\n" +
	"\x05color\x18\x02 \x01(\v2\x15.tui_example.RgbColorB-\x92\xb5\x18)\n" +
	"\x05color\x1a\x17Greeting color as R,G,BR\a\n" +
	"\x05ColorR\x05color\"M\n" +
	"\x14ColoredGreetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1b\n" +
	"\tcolor_hex\x18\x02 \x01(\tR\bcolorHex\"\xa4\x01\n" +
	"\vNoteRequest\x12=\n" +
	"\x04name\x18\x01 \x01(\tB)\x92\xb5\x18%\n" +
	"\x04name\x1a\x1bName to address the note to \x01R\x04name\x12V\n" +
	"\bmetadata\x18\x02 \x01(\tB:\x92\xb5\x186\n" +
	"\bmetadata\x1a\x17Free-form JSON metadataR\x11\n" +
	"\x0fMetadata (JSON)R\bmetadata\"D\n" +
	"\fNoteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\"\xa8\x01\n" +
	"\x13ScheduleCallRequest\x12-\n" +
	"\x04with\x18\x01 \x01(\tB\x19\x92\xb5\x18\x15\n" +
	"\x04with\x1a\vWho to call \x01R\x04with\x12b\n" +
	"\x04when\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB2\x92\xb5\x18.\n" +
	"\x04when\x1a$When to call — enter in local time \x01R\x04when\"j\n" +
	"\x14ScheduleCallResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"when_local\x18\x02 \x01(\tR\twhenLocal\x12\x19\n" +
	"\bwhen_utc\x18\x03 \x01(\tR\awhenUtc\"2\n" +
	"\n" +
	"PersonCard\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\"f\n" +
	"\x11ListPeopleRequest\x12Q\n" +
	"\x06filter\x18\x01 \x01(\tB9\x92\xb5\x185\n" +
	"\x06filter\x1a+Filter by name prefix (leave empty for all)R\x06filter2\xdb\x06\n" +
	"\x0fFarewellService\x12\x7f\n" +
	"\bFarewell\x12\x1c.tui_example.FarewellRequest\x1a\x1d.tui_example.FarewellResponse\"6\x8a\xb5\x182\n" +
	"\bfarewell\x12\x16Say goodbye to someoneR\x0e\n" +
	"\fBid Farewell\x12\xa0\x01\n" +
	"\fFarewellMany\x12 .tui_example.FarewellManyRequest\x1a!.tui_example.FarewellManyResponse\"K\x8a\xb5\x18G\n" +
	"\rfarewell-many\x12\x1eSay goodbye to multiple peopleR\x16\n" +
	"\x14Bid Farewell to Many\x12\xc5\x01\n" +
	"\x11ScheduledFarewell\x12%.tui_example.ScheduledFarewellRequest\x1a&.tui_example.ScheduledFarewellResponse\"a\x8a\xb5\x18]\n" +
	"\x12scheduled-farewell\x120Schedule a goodbye for a specific time and placeR\x15\n" +
	"\x13Schedule a Farewell\x12t\n" +
	"\tLeaveNote\x12\x18.tui_example.NoteRequest\x1a\x19.tui_example.NoteResponse\"2\x8a\xb5\x18.\n" +
	"\n" +
	"leave-note\x12 Attach a JSON note to a farewell\x12\xb6\x01\n" +
	"\x11CountdownFarewell\x12%.tui_example.CountdownFarewellRequest\x1a&.tui_example.CountdownFarewellResponse\"P\x8a\xb5\x18L\n" +
	"\x12countdown-farewell\x12 Count down to a dramatic goodbyeR\x14\n" +
	"\x12Countdown Farewell0\x01\x1a-\x82\xb5\x18)\n" +
	"\bfarewell\x12\x11Farewell commandsR\n" +
	"\n" +
	"\bFarewell2\xd2\x01\n" +
	"\x10DirectoryService\x12\x8c\x01\n" +
	"\n" +
	"ListPeople\x12\x1e.tui_example.ListPeopleRequest\x1a\x17.tui_example.PersonCard\"C\x8a\xb5\x18?\n" +
	"\vlist-people\x12\x1cBrowse the contact directoryR\x12\n" +
	"\x10Browse Directory0\x01\x1a/\x82\xb5\x18+\n" +
	"\tdirectory\x12\x11Contact directoryR\v\n" +
	"\tDirectory2\xe9\x05\n" +
	"\x0eGreeterService\x12n\n" +
	"\x05Greet\x12\x19.tui_example.GreetRequest\x1a\x1a.tui_example.GreetResponse\".\x8a\xb5\x18*\n" +
	"\x05greet\x12\x14Say hello to someoneR\v\n" +
	"\tSay Hello\x12\x98\x01\n" +
	"\rListGreetings\x12!.tui_example.ListGreetingsRequest\x1a\".tui_example.ListGreetingsResponse\"@\x8a\xb5\x18<\n" +
	"\x0elist-greetings\x12\x1cSay hello to multiple peopleR\f\n" +
	"\n" +
	"Greet Many\x12u\n" +
	"\fHiddenMethod\x12\x19.tui_example.GreetRequest\x1a\x1a.tui_example.GreetResponse\".\x8a\xb5\x18*\n" +
	"\x06hidden\x12\x1cA method hidden from the TUIR\x02\x10\x01\x12\x85\x01\n" +
	"\fColoredGreet\x12 .tui_example.ColoredGreetRequest\x1a!.tui_example.ColoredGreetResponse\"0\x8a\xb5\x18,\n" +
	"\rcolored-greet\x12\x1bSay hello in a chosen color\x12\x9f\x01\n" +
	"\fScheduleCall\x12 .tui_example.ScheduleCallRequest\x1a!.tui_example.ScheduleCallResponse\"J\x8a\xb5\x18F\n" +
	"\rschedule-call\x12\"Book a call in your local timezoneR\x11\n" +
	"\x0fSchedule a Call\x1a+\x82\xb5\x18'\n" +
	"\agreeter\x12\x11Greeting commandsR\t\n" +
	"\aGreeterB,Z*github.com/drewfead/proto-cli/examples/tuib\x06proto3"

var (
	file_examples_tui_tui_proto_rawDescOnce sync.Once
	file_examples_tui_tui_proto_rawDescData []byte
)

func file_examples_tui_tui_proto_rawDescGZIP() []byte {
	file_examples_tui_tui_proto_rawDescOnce.Do(func() {
		file_examples_tui_tui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_tui_tui_proto_rawDesc), len(file_examples_tui_tui_proto_rawDesc)))
	})
	return file_examples_tui_tui_proto_rawDescData
}

var file_examples_tui_tui_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_examples_tui_tui_proto_goTypes = []any{
	(*GreetRequest)(nil),              // 0: tui_example.GreetRequest
	(*GreetResponse)(nil),             // 1: tui_example.GreetResponse
	(*ListGreetingsRequest)(nil),      // 2: tui_example.ListGreetingsRequest
	(*ListGreetingsResponse)(nil),     // 3: tui_example.ListGreetingsResponse
	(*FarewellRequest)(nil),           // 4: tui_example.FarewellRequest
	(*FarewellResponse)(nil),          // 5: tui_example.FarewellResponse
	(*FarewellManyRequest)(nil),       // 6: tui_example.FarewellManyRequest
	(*FarewellManyResponse)(nil),      // 7: tui_example.FarewellManyResponse
	(*CountdownFarewellRequest)(nil),  // 8: tui_example.CountdownFarewellRequest
	(*CountdownFarewellResponse)(nil), // 9: tui_example.CountdownFarewellResponse
	(*DeliveryAddress)(nil),           // 10: tui_example.DeliveryAddress
	(*ScheduledFarewellRequest)(nil),  // 11: tui_example.ScheduledFarewellRequest
	(*ScheduledFarewellResponse)(nil), // 12: tui_example.ScheduledFarewellResponse
	(*RgbColor)(nil),                  // 13: tui_example.RgbColor
	(*ColoredGreetRequest)(nil),       // 14: tui_example.ColoredGreetRequest
	(*ColoredGreetResponse)(nil),      // 15: tui_example.ColoredGreetResponse
	(*NoteRequest)(nil),               // 16: tui_example.NoteRequest
	(*NoteResponse)(nil),              // 17: tui_example.NoteResponse
	(*ScheduleCallRequest)(nil),       // 18: tui_example.ScheduleCallRequest
	(*ScheduleCallResponse)(nil),      // 19: tui_example.ScheduleCallResponse
	(*PersonCard)(nil),                // 20: tui_example.PersonCard
	(*ListPeopleRequest)(nil),         // 21: tui_example.ListPeopleRequest
	(*timestamppb.Timestamp)(nil),     // 22: google.protobuf.Timestamp
}
var file_examples_tui_tui_proto_depIdxs = []int32{
	22, // 0: tui_example.ScheduledFarewellRequest.send_at:type_name -> google.protobuf.Timestamp
	10, // 1: tui_example.ScheduledFarewellRequest.address:type_name -> tui_example.DeliveryAddress
	13, // 2: tui_example.ColoredGreetRequest.color:type_name -> tui_example.RgbColor
	22, // 3: tui_example.ScheduleCallRequest.when:type_name -> google.protobuf.Timestamp
	4,  // 4: tui_example.FarewellService.Farewell:input_type -> tui_example.FarewellRequest
	6,  // 5: tui_example.FarewellService.FarewellMany:input_type -> tui_example.FarewellManyRequest
	11, // 6: tui_example.FarewellService.ScheduledFarewell:input_type -> tui_example.ScheduledFarewellRequest
	16, // 7: tui_example.FarewellService.LeaveNote:input_type -> tui_example.NoteRequest
	8,  // 8: tui_example.FarewellService.CountdownFarewell:input_type -> tui_example.CountdownFarewellRequest
	21, // 9: tui_example.DirectoryService.ListPeople:input_type -> tui_example.ListPeopleRequest
	0,  // 10: tui_example.GreeterService.Greet:input_type -> tui_example.GreetRequest
	2,  // 11: tui_example.GreeterService.ListGreetings:input_type -> tui_example.ListGreetingsRequest
	0,  // 12: tui_example.GreeterService.HiddenMethod:input_type -> tui_example.GreetRequest
	14, // 13: tui_example.GreeterService.ColoredGreet:input_type -> tui_example.ColoredGreetRequest
	18, // 14: tui_example.GreeterService.ScheduleCall:input_type -> tui_example.ScheduleCallRequest
	5,  // 15: tui_example.FarewellService.Farewell:output_type -> tui_example.FarewellResponse
	7,  // 16: tui_example.FarewellService.FarewellMany:output_type -> tui_example.FarewellManyResponse
	12, // 17: tui_example.FarewellService.ScheduledFarewell:output_type -> tui_example.ScheduledFarewellResponse
	17, // 18: tui_example.FarewellService.LeaveNote:output_type -> tui_example.NoteResponse
	9,  // 19: tui_example.FarewellService.CountdownFarewell:output_type -> tui_example.CountdownFarewellResponse
	20, // 20: tui_example.DirectoryService.ListPeople:output_type -> tui_example.PersonCard
	1,  // 21: tui_example.GreeterService.Greet:output_type -> tui_example.GreetResponse
	3,  // 22: tui_example.GreeterService.ListGreetings:output_type -> tui_example.ListGreetingsResponse
	1,  // 23: tui_example.GreeterService.HiddenMethod:output_type -> tui_example.GreetResponse
	15, // 24: tui_example.GreeterService.ColoredGreet:output_type -> tui_example.ColoredGreetResponse
	19, // 25: tui_example.GreeterService.ScheduleCall:output_type -> tui_example.ScheduleCallResponse
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_examples_tui_tui_proto_init() }
func file_examples_tui_tui_proto_init() {
	if File_examples_tui_tui_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_tui_tui_proto_rawDesc), len(file_examples_tui_tui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_examples_tui_tui_proto_goTypes,
		DependencyIndexes: file_examples_tui_tui_proto_depIdxs,
		MessageInfos:      file_examples_tui_tui_proto_msgTypes,
	}.Build()
	File_examples_tui_tui_proto = out.File
	file_examples_tui_tui_proto_goTypes = nil
	file_examples_tui_tui_proto_depIdxs = nil
}
