// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: examples/streaming/streaming.proto

package streaming

import (
	_ "github.com/drewfead/proto-cli/internal/clipb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListItemsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Category string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Limit    int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Optional fields demonstrate explicit presence tracking
	Offset         *int32  `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	SortBy         *string `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`
	IncludeDeleted *bool   `protobuf:"varint,5,opt,name=include_deleted,json=includeDeleted,proto3,oneof" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_examples_streaming_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_streaming_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_examples_streaming_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *ListItemsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListItemsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ListItemsRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *ListItemsRequest) GetIncludeDeleted() bool {
	if x != nil && x.IncludeDeleted != nil {
		return *x.IncludeDeleted
	}
	return false
}

type ItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemResponse) Reset() {
	*x = ItemResponse{}
	mi := &file_examples_streaming_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponse) ProtoMessage() {}

func (x *ItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_streaming_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponse.ProtoReflect.Descriptor instead.
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return file_examples_streaming_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *ItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_examples_streaming_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_examples_streaming_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_examples_streaming_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartId       int64                  `protobuf:"varint,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_examples_streaming_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_streaming_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_examples_streaming_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *WatchRequest) GetStartId() int64 {
	if x != nil {
		return x.StartId
	}
	return 0
}

type ItemEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "created", "updated", "deleted"
	Item          *Item                  `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemEvent) Reset() {
	*x = ItemEvent{}
	mi := &file_examples_streaming_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemEvent) ProtoMessage() {}

func (x *ItemEvent) ProtoReflect() protoreflect.Message {
	mi := &file_examples_streaming_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemEvent.ProtoReflect.Descriptor instead.
func (*ItemEvent) Descriptor() ([]byte, []int) {
	return file_examples_streaming_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *ItemEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ItemEvent) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ItemEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_examples_streaming_streaming_proto protoreflect.FileDescriptor

const file_examples_streaming_streaming_proto_rawDesc = "" +
	"\n" +
	"\"examples/streaming/streaming.proto\x12\tstreaming\x1a\x18internal/clipb/cli.proto\"\xa3\x03\n" +
	"\x10ListItemsRequest\x12>\n" +
	"\bcategory\x18\x01 \x01(\tB\"\x92\xb5\x18\x1e\n" +
	"\bcategory\x1a\x12Filter by categoryR\bcategory\x126\n" +
	"\x05limit\x18\x02 \x01(\x05B \x92\xb5\x18\x1c\n" +
	"\x05limit\x1a\x13Max items to returnR\x05limit\x12B\n" +
	"\x06offset\x18\x03 \x01(\x05B%\x92\xb5\x18!\n" +
	"\x06offset\x1a\x17Number of items to skipH\x00R\x06offset\x88\x01\x01\x12L\n" +
	"\asort_by\x18\x04 \x01(\tB.\x92\xb5\x18*\n" +
	"\asort-by\x1a\x1fSort field (name, id, category)H\x01R\x06sortBy\x88\x01\x01\x12Z\n" +
	"\x0finclude_deleted\x18\x05 \x01(\bB,\x92\xb5\x18(\n" +
	"\x0finclude-deleted\x1a\x15Include deleted itemsH\x02R\x0eincludeDeleted\x88\x01\x01B\t\n" +
	"\a_offsetB\n" +
	"\n" +
	"\b_sort_byB\x12\n" +
	"\x10_include_deleted\"M\n" +
	"\fItemResponse\x12#\n" +
	"\x04item\x18\x01 \x01(\v2\x0f.streaming.ItemR\x04item\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"V\n" +
	"\fWatchRequest\x12F\n" +
	"\bstart_id\x18\x01 \x01(\x03B+\x92\xb5\x18'\n" +
	"\bstart-id\x1a\x1bStart watching from this IDR\astartId\"m\n" +
	"\tItemEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12#\n" +
	"\x04item\x18\x02 \x01(\v2\x0f.streaming.ItemR\x04item\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2\xb2\x02\n" +
	"\x10StreamingService\x12s\n" +
	"\tListItems\x12\x1b.streaming.ListItemsRequest\x1a\x17.streaming.ItemResponse\".\x8a\xb5\x18*\n" +
	"\n" +
	"list-items\x12\x1cStream items from the server0\x01\x12u\n" +
	"\n" +
	"WatchItems\x12\x17.streaming.WatchRequest\x1a\x14.streaming.ItemEvent\"6\x8a\xb5\x182\n" +
	"\vwatch-items\x12#Watch for item changes in real-time0\x01\x1a2\x82\xb5\x18.\n" +
	"\x11streaming-service\x12\x19Example streaming serviceB\x95\x01\n" +
	"\rcom.streamingB\x0eStreamingProtoP\x01Z0github.com/drewfead/proto-cli/examples/streaming\xa2\x02\x03SXX\xaa\x02\tStreaming\xca\x02\tStreaming\xe2\x02\x15Streaming\\GPBMetadata\xea\x02\tStreamingb\x06proto3"

var (
	file_examples_streaming_streaming_proto_rawDescOnce sync.Once
	file_examples_streaming_streaming_proto_rawDescData []byte
)

func file_examples_streaming_streaming_proto_rawDescGZIP() []byte {
	file_examples_streaming_streaming_proto_rawDescOnce.Do(func() {
		file_examples_streaming_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_streaming_streaming_proto_rawDesc), len(file_examples_streaming_streaming_proto_rawDesc)))
	})
	return file_examples_streaming_streaming_proto_rawDescData
}

var file_examples_streaming_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_examples_streaming_streaming_proto_goTypes = []any{
	(*ListItemsRequest)(nil), // 0: streaming.ListItemsRequest
	(*ItemResponse)(nil),     // 1: streaming.ItemResponse
	(*Item)(nil),             // 2: streaming.Item
	(*WatchRequest)(nil),     // 3: streaming.WatchRequest
	(*ItemEvent)(nil),        // 4: streaming.ItemEvent
}
var file_examples_streaming_streaming_proto_depIdxs = []int32{
	2, // 0: streaming.ItemResponse.item:type_name -> streaming.Item
	2, // 1: streaming.ItemEvent.item:type_name -> streaming.Item
	0, // 2: streaming.StreamingService.ListItems:input_type -> streaming.ListItemsRequest
	3, // 3: streaming.StreamingService.WatchItems:input_type -> streaming.WatchRequest
	1, // 4: streaming.StreamingService.ListItems:output_type -> streaming.ItemResponse
	4, // 5: streaming.StreamingService.WatchItems:output_type -> streaming.ItemEvent
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_examples_streaming_streaming_proto_init() }
func file_examples_streaming_streaming_proto_init() {
	if File_examples_streaming_streaming_proto != nil {
		return
	}
	file_examples_streaming_streaming_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_streaming_streaming_proto_rawDesc), len(file_examples_streaming_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_streaming_streaming_proto_goTypes,
		DependencyIndexes: file_examples_streaming_streaming_proto_depIdxs,
		MessageInfos:      file_examples_streaming_streaming_proto_msgTypes,
	}.Build()
	File_examples_streaming_streaming_proto = out.File
	file_examples_streaming_streaming_proto_goTypes = nil
	file_examples_streaming_streaming_proto_depIdxs = nil
}
