// Code generated by protoc-gen-cli. DO NOT EDIT.

package streaming

import (
	"context"
	"fmt"
	protocli "github.com/drewfead/proto-cli"
	v3 "github.com/urfave/cli/v3"
	grpc "google.golang.org/grpc"
	insecure "google.golang.org/grpc/credentials/insecure"
	metadata "google.golang.org/grpc/metadata"
	"io"
	"log/slog"
	"os"
	"strings"
)

// getOutputWriter opens the specified output file or returns stdout
func getOutputWriter(path string) (io.Writer, error) {
	if path == "-" || path == "" {
		return os.Stdout, nil
	}
	return os.Create(path)
}

// localServerStream_ListItems is a helper type for local server streaming calls to ListItems
type localServerStream_ListItems struct {
	ctx       context.Context
	responses chan *ItemResponse
	errors    chan error
}

func (s *localServerStream_ListItems) Send(resp *ItemResponse) error {
	select {
	case s.responses <- resp:
		return nil
	case <-s.ctx.Done():
		return s.ctx.Err()
	}
}

func (s *localServerStream_ListItems) Context() context.Context {
	return s.ctx
}

func (s *localServerStream_ListItems) SetHeader(metadata.MD) error {
	return nil
}

func (s *localServerStream_ListItems) SendHeader(metadata.MD) error {
	return nil
}

func (s *localServerStream_ListItems) SetTrailer(metadata.MD) {}

func (s *localServerStream_ListItems) SendMsg(m any) error {
	msg, ok := m.(*ItemResponse)
	if !ok {
		return fmt.Errorf("invalid message type: expected *%s, got %T", "ItemResponse", m)
	}
	return s.Send(msg)
}

func (s *localServerStream_ListItems) RecvMsg(m any) error {
	return fmt.Errorf("RecvMsg not supported on server streaming")
}

// localServerStream_WatchItems is a helper type for local server streaming calls to WatchItems
type localServerStream_WatchItems struct {
	ctx       context.Context
	responses chan *ItemEvent
	errors    chan error
}

func (s *localServerStream_WatchItems) Send(resp *ItemEvent) error {
	select {
	case s.responses <- resp:
		return nil
	case <-s.ctx.Done():
		return s.ctx.Err()
	}
}

func (s *localServerStream_WatchItems) Context() context.Context {
	return s.ctx
}

func (s *localServerStream_WatchItems) SetHeader(metadata.MD) error {
	return nil
}

func (s *localServerStream_WatchItems) SendHeader(metadata.MD) error {
	return nil
}

func (s *localServerStream_WatchItems) SetTrailer(metadata.MD) {}

func (s *localServerStream_WatchItems) SendMsg(m any) error {
	msg, ok := m.(*ItemEvent)
	if !ok {
		return fmt.Errorf("invalid message type: expected *%s, got %T", "ItemEvent", m)
	}
	return s.Send(msg)
}

func (s *localServerStream_WatchItems) RecvMsg(m any) error {
	return fmt.Errorf("RecvMsg not supported on server streaming")
}

// StreamingServiceCommand creates a CLI for StreamingService with options
// The implOrFactory parameter can be either a direct service implementation or a factory function
func StreamingServiceCommand(ctx context.Context, implOrFactory interface{}, opts ...protocli.ServiceOption) *protocli.ServiceCLI {
	options := protocli.ApplyServiceOptions(opts...)

	// Determine default format (first registered format, or empty if none)
	var defaultFormat string
	if len(options.OutputFormats()) > 0 {
		defaultFormat = options.OutputFormats()[0].Name()
	}

	var commands []*v3.Command

	// Build flags for list-items
	flags_list_items := []v3.Flag{&v3.StringFlag{
		Name:  "remote",
		Usage: "Remote gRPC server address (host:port). If set, uses gRPC client instead of direct call",
	}, &v3.StringFlag{
		Name:  "format",
		Usage: "Output format (use --format to see available formats)",
		Value: defaultFormat,
	}, &v3.StringFlag{
		Name:  "output",
		Usage: "Output file (- for stdout)",
		Value: "-",
	}, &v3.StringFlag{
		Name:  "delimiter",
		Usage: "Delimiter between streamed messages",
		Value: "\n",
	}}

	flags_list_items = append(flags_list_items, &v3.StringFlag{
		Name:  "category",
		Usage: "Filter by category",
	})
	flags_list_items = append(flags_list_items, &v3.Int32Flag{
		Name:  "limit",
		Usage: "Max items to return",
	})

	// Add format-specific flags from registered formats
	for _, outputFmt := range options.OutputFormats() {
		// Check if format implements FlagConfiguredOutputFormat
		if flagConfigured, ok := outputFmt.(protocli.FlagConfiguredOutputFormat); ok {
			flags_list_items = append(flags_list_items, flagConfigured.Flags()...)
		}
	}

	commands = append(commands, &v3.Command{
		Action: func(cmdCtx context.Context, cmd *v3.Command) error {
			if options.BeforeCommand() != nil {
				if err := options.BeforeCommand()(cmdCtx, cmd); err != nil {
					return fmt.Errorf("before hook failed: %w", err)
				}
			}

			defer func() {
				if options.AfterCommand() != nil {
					if err := options.AfterCommand()(cmdCtx, cmd); err != nil {
						slog.Warn("after hook failed", "error", err)
					}
				}
			}()

			// Build request message
			var req *ListItemsRequest

			// Check for custom flag deserializer for streaming.ListItemsRequest
			deserializer, hasDeserializer := options.FlagDeserializer("streaming.ListItemsRequest")
			if hasDeserializer {
				// Use custom deserializer for top-level request
				requestFlags := protocli.NewFlagContainer(cmd, "")
				msg, err := deserializer(cmdCtx, requestFlags)
				if err != nil {
					return fmt.Errorf("custom deserializer failed: %w", err)
				}
				if msg == nil {
					return fmt.Errorf("custom deserializer returned nil message")
				}
				var ok bool
				req, ok = msg.(*ListItemsRequest)
				if !ok {
					return fmt.Errorf("custom deserializer returned wrong type: expected *%s, got %T", "ListItemsRequest", msg)
				}
			} else {
				// Use auto-generated flag parsing
				req = &ListItemsRequest{}
				req.Category = cmd.String("category")
				req.Limit = cmd.Int32("limit")
			}

			// Open output writer
			outputWriter, err := getOutputWriter(cmd.String("output"))
			if err != nil {
				return fmt.Errorf("failed to open output: %w", err)
			}
			if closer, ok := outputWriter.(io.Closer); ok {
				defer closer.Close()
			}

			// Find the appropriate output format
			formatName := cmd.String("format")
			var outputFmt protocli.OutputFormat
			for _, f := range options.OutputFormats() {
				if f.Name() == formatName {
					outputFmt = f
					break
				}
			}
			if outputFmt == nil {
				var availableFormats []string
				for _, f := range options.OutputFormats() {
					availableFormats = append(availableFormats, f.Name())
				}
				return fmt.Errorf("unknown format %q (available: %v)", formatName, availableFormats)
			}

			// Get delimiter for separating streamed messages
			delimiter := cmd.String("delimiter")

			// Check if using remote gRPC call or direct implementation call
			remoteAddr := cmd.String("remote")

			if remoteAddr != "" {
				// Remote gRPC streaming call
				conn, connErr := grpc.NewClient(remoteAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
				if connErr != nil {
					return fmt.Errorf("failed to connect to remote %s: %w", remoteAddr, connErr)
				}
				defer conn.Close()

				client := NewStreamingServiceClient(conn)
				stream, err := client.ListItems(cmdCtx, req)
				if err != nil {
					return fmt.Errorf("failed to start stream: %w", err)
				}

				// Receive and format each message in the stream
				var messageCount int
				for {
					msg, recvErr := stream.Recv()
					if recvErr == io.EOF {
						break
					}
					if recvErr != nil {
						return fmt.Errorf("stream receive error: %w", recvErr)
					}

					// Format and write the message
					if err := outputFmt.Format(cmdCtx, cmd, outputWriter, msg); err != nil {
						return fmt.Errorf("format failed: %w", err)
					}

					// Write delimiter
					if _, err := outputWriter.Write([]byte(delimiter)); err != nil {
						return fmt.Errorf("failed to write delimiter: %w", err)
					}
					messageCount++
				}

				// Write final newline to keep terminal clean (only if delimiter doesn't already end with newline)
				if messageCount > 0 && !strings.HasSuffix(delimiter, "\n") {
					if _, err := outputWriter.Write([]byte("\n")); err != nil {
						return fmt.Errorf("failed to write final newline: %w", err)
					}
				}
			} else {
				// Direct implementation call (no config)
				svcImpl := implOrFactory.(StreamingServiceServer)

				// Create local stream wrapper for direct call
				localStream := &localServerStream_ListItems{
					ctx:       cmdCtx,
					errors:    make(chan error),
					responses: make(chan *ItemResponse),
				}

				// Call streaming method in goroutine
				go func() {
					var methodErr error
					methodErr = svcImpl.ListItems(req, localStream)
					close(localStream.responses)
					if methodErr != nil {
						localStream.errors <- methodErr
					}
					close(localStream.errors)
				}()

				// Receive and format each message in the stream
				var messageCount int
				for {
					select {
					case msg, ok := <-localStream.responses:
						if !ok {
							// Stream closed, check for errors
							if streamErr := <-localStream.errors; streamErr != nil {
								return fmt.Errorf("stream error: %w", streamErr)
							}
							// Write final newline to keep terminal clean (only if delimiter doesn't already end with newline)
							if messageCount > 0 && !strings.HasSuffix(delimiter, "\n") {
								if _, err := outputWriter.Write([]byte("\n")); err != nil {
									return fmt.Errorf("failed to write final newline: %w", err)
								}
							}
							return nil
						}

						// Format and write the message
						if err := outputFmt.Format(cmdCtx, cmd, outputWriter, msg); err != nil {
							return fmt.Errorf("format failed: %w", err)
						}

						// Write delimiter
						if _, err := outputWriter.Write([]byte(delimiter)); err != nil {
							return fmt.Errorf("failed to write delimiter: %w", err)
						}
						messageCount++
					case <-cmdCtx.Done():
						return cmdCtx.Err()
					}
				}
			}

			return nil
		},
		Flags: flags_list_items,
		Name:  "list-items",
		Usage: "Stream items from the server",
	})

	// Build flags for watch-items
	flags_watch_items := []v3.Flag{&v3.StringFlag{
		Name:  "remote",
		Usage: "Remote gRPC server address (host:port). If set, uses gRPC client instead of direct call",
	}, &v3.StringFlag{
		Name:  "format",
		Usage: "Output format (use --format to see available formats)",
		Value: defaultFormat,
	}, &v3.StringFlag{
		Name:  "output",
		Usage: "Output file (- for stdout)",
		Value: "-",
	}, &v3.StringFlag{
		Name:  "delimiter",
		Usage: "Delimiter between streamed messages",
		Value: "\n",
	}}

	flags_watch_items = append(flags_watch_items, &v3.Int64Flag{
		Name:  "start-id",
		Usage: "Start watching from this ID",
	})

	// Add format-specific flags from registered formats
	for _, outputFmt := range options.OutputFormats() {
		// Check if format implements FlagConfiguredOutputFormat
		if flagConfigured, ok := outputFmt.(protocli.FlagConfiguredOutputFormat); ok {
			flags_watch_items = append(flags_watch_items, flagConfigured.Flags()...)
		}
	}

	commands = append(commands, &v3.Command{
		Action: func(cmdCtx context.Context, cmd *v3.Command) error {
			if options.BeforeCommand() != nil {
				if err := options.BeforeCommand()(cmdCtx, cmd); err != nil {
					return fmt.Errorf("before hook failed: %w", err)
				}
			}

			defer func() {
				if options.AfterCommand() != nil {
					if err := options.AfterCommand()(cmdCtx, cmd); err != nil {
						slog.Warn("after hook failed", "error", err)
					}
				}
			}()

			// Build request message
			var req *WatchRequest

			// Check for custom flag deserializer for streaming.WatchRequest
			deserializer, hasDeserializer := options.FlagDeserializer("streaming.WatchRequest")
			if hasDeserializer {
				// Use custom deserializer for top-level request
				requestFlags := protocli.NewFlagContainer(cmd, "")
				msg, err := deserializer(cmdCtx, requestFlags)
				if err != nil {
					return fmt.Errorf("custom deserializer failed: %w", err)
				}
				if msg == nil {
					return fmt.Errorf("custom deserializer returned nil message")
				}
				var ok bool
				req, ok = msg.(*WatchRequest)
				if !ok {
					return fmt.Errorf("custom deserializer returned wrong type: expected *%s, got %T", "WatchRequest", msg)
				}
			} else {
				// Use auto-generated flag parsing
				req = &WatchRequest{}
				req.StartId = cmd.Int64("start-id")
			}

			// Open output writer
			outputWriter, err := getOutputWriter(cmd.String("output"))
			if err != nil {
				return fmt.Errorf("failed to open output: %w", err)
			}
			if closer, ok := outputWriter.(io.Closer); ok {
				defer closer.Close()
			}

			// Find the appropriate output format
			formatName := cmd.String("format")
			var outputFmt protocli.OutputFormat
			for _, f := range options.OutputFormats() {
				if f.Name() == formatName {
					outputFmt = f
					break
				}
			}
			if outputFmt == nil {
				var availableFormats []string
				for _, f := range options.OutputFormats() {
					availableFormats = append(availableFormats, f.Name())
				}
				return fmt.Errorf("unknown format %q (available: %v)", formatName, availableFormats)
			}

			// Get delimiter for separating streamed messages
			delimiter := cmd.String("delimiter")

			// Check if using remote gRPC call or direct implementation call
			remoteAddr := cmd.String("remote")

			if remoteAddr != "" {
				// Remote gRPC streaming call
				conn, connErr := grpc.NewClient(remoteAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
				if connErr != nil {
					return fmt.Errorf("failed to connect to remote %s: %w", remoteAddr, connErr)
				}
				defer conn.Close()

				client := NewStreamingServiceClient(conn)
				stream, err := client.WatchItems(cmdCtx, req)
				if err != nil {
					return fmt.Errorf("failed to start stream: %w", err)
				}

				// Receive and format each message in the stream
				var messageCount int
				for {
					msg, recvErr := stream.Recv()
					if recvErr == io.EOF {
						break
					}
					if recvErr != nil {
						return fmt.Errorf("stream receive error: %w", recvErr)
					}

					// Format and write the message
					if err := outputFmt.Format(cmdCtx, cmd, outputWriter, msg); err != nil {
						return fmt.Errorf("format failed: %w", err)
					}

					// Write delimiter
					if _, err := outputWriter.Write([]byte(delimiter)); err != nil {
						return fmt.Errorf("failed to write delimiter: %w", err)
					}
					messageCount++
				}

				// Write final newline to keep terminal clean (only if delimiter doesn't already end with newline)
				if messageCount > 0 && !strings.HasSuffix(delimiter, "\n") {
					if _, err := outputWriter.Write([]byte("\n")); err != nil {
						return fmt.Errorf("failed to write final newline: %w", err)
					}
				}
			} else {
				// Direct implementation call (no config)
				svcImpl := implOrFactory.(StreamingServiceServer)

				// Create local stream wrapper for direct call
				localStream := &localServerStream_WatchItems{
					ctx:       cmdCtx,
					errors:    make(chan error),
					responses: make(chan *ItemEvent),
				}

				// Call streaming method in goroutine
				go func() {
					var methodErr error
					methodErr = svcImpl.WatchItems(req, localStream)
					close(localStream.responses)
					if methodErr != nil {
						localStream.errors <- methodErr
					}
					close(localStream.errors)
				}()

				// Receive and format each message in the stream
				var messageCount int
				for {
					select {
					case msg, ok := <-localStream.responses:
						if !ok {
							// Stream closed, check for errors
							if streamErr := <-localStream.errors; streamErr != nil {
								return fmt.Errorf("stream error: %w", streamErr)
							}
							// Write final newline to keep terminal clean (only if delimiter doesn't already end with newline)
							if messageCount > 0 && !strings.HasSuffix(delimiter, "\n") {
								if _, err := outputWriter.Write([]byte("\n")); err != nil {
									return fmt.Errorf("failed to write final newline: %w", err)
								}
							}
							return nil
						}

						// Format and write the message
						if err := outputFmt.Format(cmdCtx, cmd, outputWriter, msg); err != nil {
							return fmt.Errorf("format failed: %w", err)
						}

						// Write delimiter
						if _, err := outputWriter.Write([]byte(delimiter)); err != nil {
							return fmt.Errorf("failed to write delimiter: %w", err)
						}
						messageCount++
					case <-cmdCtx.Done():
						return cmdCtx.Err()
					}
				}
			}

			return nil
		},
		Flags: flags_watch_items,
		Name:  "watch-items",
		Usage: "Watch for item changes in real-time",
	})

	return &protocli.ServiceCLI{
		Command: &v3.Command{
			Commands: commands,
			Name:     "streaming-service",
			Usage:    "Example streaming service",
		},
		ConfigMessageType: "",
		FactoryOrImpl:     implOrFactory,
		RegisterFunc: func(s *grpc.Server, impl interface{}) {
			RegisterStreamingServiceServer(s, impl.(StreamingServiceServer))
		},
		ServiceName: "streaming-service",
	}
}
